### ISSUE TITLE
Clarification on possible typo / mistake in guide

### ISSUE THREAD

**Issue by idl99** [allenai/allennlp-guide#159]
Under Common Architectures -> Section 2 - [Contextualizing Sequences](https://guide.allennlp.org/common-architectures#2), the diagram is as follows,

![image](https://user-images.githubusercontent.com/27432836/110230531-a4d0ac80-7f37-11eb-8ddf-9fb9be19b820.png)

However, shouldn't it be ```Seq2SeqEncoder``` instead of ```Seq2VecEncoder``` here?

**Comment by dirkgr** [comment]
@matt-gardner, do you have the original images somewhere, so we can fix this?

**Comment by matt-gardner** [comment]
Hmm, good catch.  I didn't make those images, Masato did.  For one of the chapters that I wrote, I recreated the visual style in a google drawing easy enough, and I can share that with you, but it's not for this image.  Or perhaps @mhagiwara still has them somewhere?

**Comment by mhagiwara** [comment]
Oops, this is my bad. #160

**Comment by dirkgr** [comment]
Thanks, merged!

@mhagiwara, can we have access to the original pictures? In case you're not available, I'd like to have the option of doing this ourselves.

**Comment by mhagiwara** [comment]
@dirkgr Yeah good idea. I just email them to you and @matt-gardner

**Comment by idl99** [comment]
Thanks everyone 👍 I'm closing this issue now that it's resolved.
