### ISSUE TITLE
Broken link on Guide Part 2 - Reading data for TriviaQaReader

### ISSUE THREAD

**Issue by benoit-intrw** [allenai/allennlp-guide#164]
Hello,

The link to [TriviaQaReader](https://github.com/allenai/allennlp-models/blob/main/allennlp_models/rc/other/triviaqa_reader.py)  in https://guide.allennlp.org/reading-data#2 is 404

Source are here https://github.com/allenai/allennlp-guide/blame/master/chapters/part2/reading-data.md#L122 (Sorry to link to blame page, but with markdown preview it is not possible to link a line)

Is the following link a correct substitute ? https://github.com/allenai/allennlp-reading-comprehension/blob/master/allennlp_rc/dataset_readers/triviaqa.py#L21

Regards.

**Comment by epwalsh** [comment]
Hi @benoit-intrw, thanks for pointing that out. The correct link is actually https://github.com/allenai/allennlp-models/blob/main/allennlp_models/rc/dataset_readers/triviaqa.py#L21.

I'll update this right now.

**Comment by epwalsh** [comment]
Closed by 2beb154703ec0add121b8979716ab298b0bfe615
