### ISSUE TITLE
Add a section to explain where to obtain example files etc.

### ISSUE THREAD

**Issue by david-waterworth** [allenai/allennlp-guide#168]
I'm a new user to allennlp, I've been doing ML / NLP for some time though. It's always hard knowing where to start, so this guide is great. But as far as I can see there's no link in the guide itself (https://guide.allennlp.org/) back to this repo. In particular fairly early on the examples try and load `quick_start/data/movie_review/train.tsv`. I couldn't find any reference in the guide as to how to obtain these files. It took a bit of searching to find this repo.

I would suggest there's a getting started section which explains how to setup your environment so the examples work (perhaps in the overview). Maybe which minimum version of python is required, how to install allennlp and any other libraries the guide requires, and where to obtain the sample data.

**Comment by epwalsh** [comment]
Thanks for the input, @david-waterworth, that's a great point. Would you be interested in making a PR to add this info somewhere? If not, one of us can get to it soon.
