### ISSUE TITLE
Quick Start examples fail due to `Input, output and indices must be on the current device`

### ISSUE THREAD

**Issue by david-waterworth** [allenai/allennlp-guide#169]
I cannot run the example `quick_start/train.py`. It throws `Input, output and indices must be on the current device` in the forward method of SimpleClassifier (specifically the embedder). What seems to have happened is the data is automatically transferred to my GPU but the model isn't.

It seems that there should be explicit code in the example to detect if cuda is available and ensure everything is on the same device. I understand this is a tutorial so you want to keep it simple but it should run out of the box (perhaps by default set everything up for `cpu`?).

(Or is this a bug? https://docs.allennlp.org/main/api/training/trainer/ says "If you are training your model using GPUs, your model should already be on the correct device. (If you are using our train command this will be handled for you." seems to imply that it should have moved the model automatically)

**Comment by david-waterworth** [comment]
I did a bit of digging, and raise https://github.com/allenai/allennlp/issues/5186

I think the quick_start/train.py should pass `cuda_device = -1` to trainer.train, i.e. 

    trainer = GradientDescentTrainer(
        model=model,
        serialization_dir=serialization_dir,
        data_loader=train_loader,
        validation_data_loader=dev_loader,
        num_epochs=5,
        optimizer=optimizer,
        cuda_device=-1
    )

This ensures that since the model is on the cpu, and the default for is cuda_device=None (despite the documentation implying it's -1 for cpu) the trainer won't set it's the internal cuda_device field to 'cuda' if you have a gpu but not actually move the model.

**Comment by epwalsh** [comment]
Thanks @david-waterworth, https://github.com/allenai/allennlp-guide/pull/170 should fix.
