### ISSUE TITLE
How to use the distributeparallel, not trainer in Configuration files

### ISSUE THREAD

**Issue by syiswell** [allenai/allennlp-guide#184]
Please tell me how to use the distribute parallel for the model from THE ALLENAI. NOT trainer in Configuration files because I don't use it.
I try to use nn.DataParallel or nn.DistributedDataParallel, but it obviously doesn't work and report some error.

Thank you
Yours sincerely！

**Comment by epwalsh** [comment]
Hi, information on how to use `torch.distributed` directly is outside the scope of this guide. I'd recommend reading through [the PyTorch docs](https://pytorch.org/tutorials/beginner/dist_overview.html).

**Comment by syiswell** [comment]
> Hi, information on how to use `torch.distributed` directly is outside the scope of this guide. I'd recommend reading through [the PyTorch docs](https://pytorch.org/tutorials/beginner/dist_overview.html).

Sir, I know what you mean. In fact，I have already tried to directly use the 'torch.distributed' for the model implemented by the ALLENAI. But when I call the method of the model, it reports "AttributeError: DataParallel object has no attribute 'embde_sentenses' ".
Thank you for your reply!

**Comment by epwalsh** [comment]
It's hard to figure out how to give you advice when I don't know what you're doing. Can you please provide code snippets, environment details, and full stack traces. And for future reference, a better place to ask questions like this would be the [AllenNLP Discussions Q&A](https://github.com/allenai/allennlp/discussions/categories/q-a).
